/**
 * Database type definitions for MiniERP.
 *
 * These types were manually created to match the schema defined in
 * supabase/migrations/20260721010000_initial_schema.sql.
 * They are NOT auto-generated by supabase gen types.
 *
 * Each table has three interfaces:
 * - Row:     shape of a row when SELECTed
 * - Insert:  shape accepted by INSERT (id, created_at, updated_at optional)
 * - Update:  shape accepted by UPDATE (all fields optional)
 *
 * Relationships are typed as empty arrays since they are not needed for
 * the typed Supabase client query builder.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type EstadoProyecto = "Planeado" | "En progreso" | "Completado";
export type EstadoTarea = "Pendiente" | "En progreso" | "Completada";
export type EstadoEmpleado = "Activo" | "Inactivo";
export type Prioridad = "Baja" | "Media" | "Alta";

export interface Database {
  public: {
    Tables: {
      clientes: {
        Row: {
          id: string;
          nombre: string;
          nit: string | null;
          email: string | null;
          telefono: string | null;
          direccion: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          nit?: string | null;
          email?: string | null;
          telefono?: string | null;
          direccion?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          nit?: string | null;
          email?: string | null;
          telefono?: string | null;
          direccion?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      empleados: {
        Row: {
          id: string;
          nombre: string;
          email: string;
          rol: string;
          estado: EstadoEmpleado;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          email: string;
          rol: string;
          estado?: EstadoEmpleado;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          email?: string;
          rol?: string;
          estado?: EstadoEmpleado;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      proyectos: {
        Row: {
          id: string;
          nombre: string;
          cliente_id: string;
          descripcion: string | null;
          fecha_inicio: string;
          fecha_entrega: string;
          prioridad: Prioridad | null;
          estado: EstadoProyecto;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          cliente_id: string;
          descripcion?: string | null;
          fecha_inicio: string;
          fecha_entrega: string;
          prioridad?: Prioridad | null;
          estado?: EstadoProyecto;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          cliente_id?: string;
          descripcion?: string | null;
          fecha_inicio?: string;
          fecha_entrega?: string;
          prioridad?: Prioridad | null;
          estado?: EstadoProyecto;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tareas: {
        Row: {
          id: string;
          titulo: string;
          descripcion: string | null;
          proyecto_id: string;
          empleado_id: string | null;
          prioridad: Prioridad | null;
          fecha_limite: string | null;
          estado: EstadoTarea;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          titulo: string;
          descripcion?: string | null;
          proyecto_id: string;
          empleado_id?: string | null;
          prioridad?: Prioridad | null;
          fecha_limite?: string | null;
          estado?: EstadoTarea;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          titulo?: string;
          descripcion?: string | null;
          proyecto_id?: string;
          empleado_id?: string | null;
          prioridad?: Prioridad | null;
          fecha_limite?: string | null;
          estado?: EstadoTarea;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      proyecto_empleado: {
        Row: {
          id: string;
          proyecto_id: string;
          empleado_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          proyecto_id: string;
          empleado_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          proyecto_id?: string;
          empleado_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
}
